[normal]
black   = "#000000"
red     = "#fc4346"
green   = "#50fb7c"
yellow  = "#f0fb8c"
blue    = "#49baff"
magenta = "#fc4cb4"
cyan    = "#8be9fe"
white   = "#ededec"

[bright]
black   = "#555555"
red     = "#fc4346"
green   = "#50fb7c"
yellow  = "#f0fb8c"
blue    = "#49baff"
magenta = "#fc4cb4"
cyan    = "#8be9fe"
white   = "#ededec"
